### ISSUE TITLE
Change user authorization to JWT

### ISSUE THREAD

**Issue by sissyemma** [SissAcademy/SA-backend-dev#1]
Currently the authorization of the user is done storing it in the HTTP session. This will require to store in a DB like Redis or similar if we want to launch multiple backend instances.

The idea is to use JWT tokens to keep the backend stateless and being able to run as many backend instances like needed without needing external systems to keep sessions.

From the user perspective it will be the same and REST endpoints will stay the same.

**Comment by ghost** [comment]
Done
